### ISSUE TITLE
Minor typo on "Comapre" Snapshots

### ISSUE THREAD

**Issue by Fryguy** [code-mancers/rbkit-client#143]
It's a minor typo, but it's not just the presentation text...it's all the way into the code and even the file names.  I'll submit a PR if you are ok with me changing it in the code as well...

See https://github.com/code-mancers/rbkit-client/search?utf8=%E2%9C%93&q=Comapre

**Comment by gnufied** [comment]
Well spotted. Yes, I would gladly merge that. :-)
