### ISSUE TITLE
Implement CPU profiling UI for frontend

### ISSUE THREAD

**Issue by gnufied** [code-mancers/rbkit-client#153]
Once UI has been figured out as part of https://github.com/code-mancers/rbkit-client/issues/148 ticket. We need to implement it.

**Comment by iffyuva** [comment]
simple ui which can get us started:

i like the idea of showing a flame-graph, and start drill down based on it. flame graph wont be realtime one. once user stops cpu-profiling, a window of this sort will be displayed.

![mockup](https://cloud.githubusercontent.com/assets/1108398/6510392/c5fe4b42-c38b-11e4-8447-26b35fb2ab49.png)

**Comment by ishankhare07** [comment]
finalising this UI

![screen shot 2015-06-25 at 4 51 42 pm](https://cloud.githubusercontent.com/assets/7482025/8372903/55482288-1c05-11e5-8951-ecd3b18441d7.png)
